config/routes.rb
Rails.application.routes.draw do

   root 'products#index'
   
   resources :products, only: [:new, :create, :edit, :update, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  validates :title, :price, presence: true
  validates :title, uniqueness: true
  
  def display_price
    price/100.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit
    @product = Product.find(params[:id])
    
  end
  
  def destroy
    @product = Product.find(params[:id])
    
    @product.destroy
    flash[:notice] = "Product #{@product.title} elminated"
    redirect_to root_path
    
  end
  
  def update
    @product = Product.find(params[:id])
    
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  
  
  private 
  
  def product_params
    params.require(:product).permit(:title, :price)
  end
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if flash[:notice] %>
    <div class ="flash-message">
      <%= flash[:notice] %>
      
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
    
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
    
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "shared/error_messages", object: @product %>


<%= render "form" %> or <%= link_to 'delete', product_path(@product), method: :delete, data: {confirm: "Are you certain?"} %>

app/views/products/index.html.erb
<h1>Mos Corner Store</h1>
<h3>You will never  find a more wretched hive of plums and kitchenry</h3>

<%= link_to 'Send us your products!', new_product_path %>
  
<ul>
  <% for product in @products %>
   <li><%= product.title %> <%= number_to_currency(product.display_price)  %> Credits <%= link_to "edit", edit_product_path(product) %> </li>
  
  
  <% end %>
</ul>  

app/views/products/new.html.erb
<h1>Send us your products!</h1>

<%= render "shared/error_messages", object: @product %>

<%= render "form" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
    <% end %>
  </ul
<% end %>